### PR TITLE
Initial import

### PR DESCRIPTION
**Pull request by sagikazarmark**
Imports common serialization logic from the main repository.

@lstrojny I need some feedback for a few things:
- I removed (aka. didn't import) Base64Interface, but I am not sure about that.
- What is the type of [this](https://github.com/fxmlrpc/serialization/compare/initial_import?expand=1#diff-afbc6db825ae6681d2ba0833d2011a29R21) parameter?

I am also curious about your overall feedback: package architecture, licensing, etc.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I also wonder of the exceptions are fine this way.

(For the record: my plan is to have a general interface which should be implemented on all exceptions in fXmlRpc)

I mean, not all of them are used both Parser/Serializer. I am thinking about moving them to the package where it is used and renaming from Parser/Serializer exception to InvalidType and UnexpectedTag exceptions.

@lstrojny What do you think?

**Comment by lstrojny** [comment]
Can we reintroduce the Base64Interface? It’s there so that I can implement it if I have a Base64 type already in my system

**Comment by sagikazarmark** [comment]
We can, but does it really make sense? I mean, why is it any better to have a custom Base64 implementation which have to implement an interface anyway than using the provided value object?

**Comment by lstrojny** [comment]
@sagikazarmark all kinds of reasons. Let’s say you have an `Image` object that reads from the disk and does that in streaming fashion or a binary type that already comes in a different representation that you don’t want to manually convert and so on.

**Comment by sagikazarmark** [comment]
Okay, I got it. Will add it back.

**Pull request merged**
